kind: ConfigMap
apiVersion: v1
metadata:
  name: index.html
immutable: false
data:
  index.html: |-
    <html>
       <head>
         <title>Helm Chart Application</title>
         <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
         <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
       </head>
       <body>
       </div>
         <div style="margin:100px;">
          
       <class="navbar navbar-inverse navbar-static-top">
         <div class="container">
           <a class="navbar-brand" href="/">Helm Chart Application</a>
           <ul class="nav navbar-nav">
             <li class="active">
               <a href="/">Home</a>
             </li>
             <li>
               <a href="/health/liveliness">Check liveliness</a>
             </li>
             <li>
               <a href="/health/readiness">Check readiness</a>
             </li>
           </ul>
         </div>
       </nav>
           <div class="jumbotron"  style="padding:40px;">
             <img src="https://developers.redhat.com/sites/default/files/styles/article_feature/public/blog/2018/05/openshift-featured.png?   itok=g0Ee8H1H" alt="OpenShift">
             <img src="https://www.nclouds.com/img/services/toolkit/argocd.png">
             <img src="https://raw.githubusercontent.com/rhilconsultants/Application-Deployment-Workshop/main/Class%20artifacts/helm-icon-color.png">
             <h1>Hello, world!</h1>
             <h2>Our New web site, Deployed with HELM and ArgoCD.</h2>
         </div>
       </body>
       </html>
       ```
    
       Now push all those changes to the Repository
    
       ```Bash
       git add .
       git commit -m "added probes and updated the web site"
       ```
    
    5. Refrash the argoCD ui and let the application to sync.
    
       - Now refresh or Open the URL again to see the new web site.
       ![Testing Probes](https://raw.githubusercontent.com/rhilconsultants/Application-Deployment-Workshop/main/Class%20artifacts/lab2-part2-web1.png)
       - Now lets test our probes to see if they are responding.
         - on the top part of the website there is a "Check liveliness" and "Check Readiness" links.
         - Click on the "Check Liveliness" and it should show "Healty"
         - Click on the "Check Readiness" and is should show "Ready"
    
    6. Testing the Functionality of the Probes.
    
       - Lets add to our web some buttons to test our probes.
    
       ```html
       <html>
         <head>
           <title>Helm Chart Application</title>
           <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
           <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
           <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
           <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
       </head>
       <body>
       
       </div>
           <div style="margin:100px;">
       
         <class="navbar navbar-inverse navbar-static-top">
           <div class="container">
             <a class="navbar-brand" href="/">Helm Chart Application</a>
             <ul class="nav navbar-nav">
               <li class="active">
                 <a href="/">Home</a>
             </li>
               <li>
                 <a href="/health/liveliness">Check liveliness</a>
             </li>
               <li>
                 <a href="/health/readiness">Check readiness</a>
             </li>
           </ul>
         </div>
       </nav>
             <div class="jumbotron"  style="padding:40px;">
               <img src="https://developers.redhat.com/sites/default/files/styles/article_feature/public/blog/2018/05/openshift-featured.png?      itok=g0Ee8H1H" alt="OpenShift">
               <img src="https://www.nclouds.com/img/services/toolkit/argocd.png">
               <img src="https://raw.githubusercontent.com/rhilconsultants/Application-Deployment-Workshop/main/Class%20artifacts/helm-icon-color.png">
               <h1>Hello, world!</h1>
               <h2>Our New web site, Deployed with HELM and ArgoCD.</h2>
               <h3>Testing Probes buttons</h3>
               <p><a class="btn btn-primary btn-lg" href="/liveliness/400" role="button">Set Not Healty</a></p> 
               <p><a class="btn btn-primary btn-lg" href="/health/liveliness" role="button">Check liveliness</a></p>
               <p><a class="btn btn-primary btn-lg" href="/readiness/400" role="button">Set Not Ready</a></p>
               <p><a class="btn btn-primary btn-lg" href="/health/readiness" role="button">Check readiness</a></p>
         </div>
       </body>
       </html>